### ISSUE TITLE
Makefile:2033: recipe for target 'jni' failed

### ISSUE THREAD

**Issue by Gavin1993** [rhdunn/espeak#101]
[mips] SharedLibrary  : libttsespeak.so
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/compiledata.o: In function `LookupEnvelopeName':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/compiledata.c:2702: undefined reference to `LookupMnem'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/compiledict.o: In function `compile_line':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/compiledict.c:437: undefined reference to `LookupMnem'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/compiledict.o: In function `print_dictionary_flags':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/compiledict.c:194: undefined reference to `LookupMnemName'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/compiledict.c:187: undefined reference to `LookupMnemName'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/compiledict.o: In function `DecodeRule':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/compiledict.c:289: undefined reference to `LookupMnemName'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o: In function `Eof':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:242: undefined reference to `text_decoder_eof'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o: In function `GetC':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: undefined reference to `text_decoder_getc'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o: In function `ProcessSsmlTag':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:1291: undefined reference to `LookupMnem'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:1291: undefined reference to `LookupMnem'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o: In function `ReplaceKeyName':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:1190: undefined reference to `LookupMnem'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o: In function `GetC':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: undefined reference to `text_decoder_getc'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: undefined reference to `text_decoder_getc'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: undefined reference to `text_decoder_getc'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:250: undefined reference to `text_decoder_getc'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: undefined reference to `text_decoder_getc'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o:/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: more undefined references to `text_decoder_getc' follow
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o: In function `ReadClause':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:1723: undefined reference to `LookupMnem'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/readclause.o: In function `GetC':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: undefined reference to `text_decoder_getc'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/readclause.c:256: undefined reference to `text_decoder_getc'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/translate.o: In function `init_wstring_decoder':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/translate.c:1921: undefined reference to `text_decoder_decode_wstring'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/translate.o: In function `init_string_decoder':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/translate.c:1926: undefined reference to `text_decoder_decode_string'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/translate.c:1926: undefined reference to `text_decoder_decode_string'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/translate.c:1926: undefined reference to `text_decoder_decode_string'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/translate.o: In function `TranslateClause':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/translate.c:2716: undefined reference to `text_decoder_get_buffer'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/translate.c:1981: undefined reference to `create_text_decoder'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/voices.o: In function `ReadVoiceFile':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/voices.c:299: undefined reference to `LookupMnem'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/voices.c:331: undefined reference to `LookupMnem'
./obj/local/mips/objs/ttsespeak/__/__/src/libespeak-ng/voices.o: In function `LoadVoice':
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/voices.c:608: undefined reference to `LookupMnem'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/voices.c:770: undefined reference to `LookupMnem'
/home/ubuntu/data/espeak/espeak-master/android/jni/../../src/libespeak-ng/voices.c:665: undefined reference to `LookupMnem'
collect2: error: ld returned 1 exit status
make[1]: *** [obj/local/mips/libttsespeak.so] Error 1
make[1]: Leaving directory `/home/ubuntu/data/espeak/espeak-master/android'
Makefile:2033: recipe for target 'jni' failed
make: *** [jni] Error 2

**Comment by rhdunn** [comment]
I have updated the Android build files so that the Android build works again.

Thanks for the bug report.
