### ISSUE TITLE
I need Documentation of eSpeak NG DLL

### ISSUE THREAD

**Issue by shadyar** [rhdunn/espeak#110]
Hello
I am the developer of Persian language of eSpeak.
I need to use eSpeak dll in one of my programs. I got it but I do not know its function names and parameters.
is there a Documentation of eSpeak NG DLL?
please assist me, 
describe how I should convert text to speech using that dll?
kind regards

Shadyar Khodayari

**Comment by rhdunn** [comment]
https://github.com/rhdunn/espeak/blob/master/src/include/espeak-ng/speak_lib.h

NOTE: Because espeak and espeak-ng are GPLv3 licensed, your program would need to be licensed under the same terms.
