### ISSUE TITLE
Would it be hard to make a .phtrans file for the mbrola-cn1 voice?

### ISSUE THREAD

**Issue by Des-Nerger** [rhdunn/espeak#114]

**Comment by Des-Nerger** [comment]
Oh, I guess I'd better to ask it in espeak-ng/espeak-ng. Not sure if it's now a separated project or not though...

**Comment by rhdunn** [comment]
You can raise issues on either -- I am mirroring the code between the two. This was for my changes to espeak before creating espeak-ng.
