### ISSUE TITLE
When to improve the voice quality ^_^?

### ISSUE THREAD

**Issue by lostsearover** [rhdunn/espeak#122]

**Comment by rhdunn** [comment]
Can you be more specific? Vague things like this cannot be fixed as you are not describing what needs fixing. It is like saying "the Toyota car needs improving".

Specifically:
1. Is your issue with the pronunciation? If so, what is being mispronounced?
1. Is your issue with the actual sounds? If so, are there specific things that don't sound right (e.g. it is clipped), or is it a more general issue of not liking the base voice when compared to other TTS voices?
1. Can you provide examples -- words or phrases that don't sound right?

Additionally, it is useful to know what version of eSpeak/eSpeak NG, which language, and which voice (variant) you are using. This is to help try and replicate any issues you are having.
