### ISSUE TITLE
Is espeak tts supports Telugu language

### ISSUE THREAD

**Issue by vishwanadkavitha** [rhdunn/espeak#67]
Actually I am developing android application,it displays some information from db as text , when you click on that button it should speaks that text. right now it is working fine in english, I want to speak that text in telugu. With espeak is it possible, is it converts the text from english to telugu. If I choose the language as telugu it speaks the text in english means the telugu word written in english. My text contains numbers , I want to speak these numbers in telugu like 20-- IRVAI .Please calrify these. Thank you.

**Comment by rhdunn** [comment]
The eSpeak TTS engine supports Telugu. You need to ensure that the TTS engine is configured to speak Telugu, for example:

    Locale telugu = new Locale("tel");
    if (mTts.setLanguage(telugu) != TextToSpeech.LANG_AVAILABLE)
        ; // Telugu is not supported by the TTS engine, report an error

If you don't do this, eSpeak will use the language specified by the user in the TTS settings option.

The eSpeak rules for Telugu uses the Telugu script, so you will need to specify words in that script. eSpeak has a feature for non-Latin languages where it uses English to speak Latin text. It should pronounce the numbers correctly.

**Comment by vishwanadkavitha** [comment]
Thankyou for your information. I have one last question , We are developing the app for android that needs to speak out the text in telugu. Espeak tts supports telugu language not for free, I have to pay some money that is ok for me. My question is If that tts is working  for all the phones in which my app is installed or I need to install in each and every phone. Is there any library we can use in our application.Thank You
Regards,Kavitha 

     On Thursday, February 26, 2015 5:50 PM, Reece Dunn <notifications@github.com> wrote:
   

 The eSpeak TTS engine supports Telugu. You need to ensure that the TTS engine is configured to speak Telugu, for example:Locale telugu = new Locale("tel");
if (mTts.setLanguage(telugu) != TextToSpeech.LANG_AVAILABLE)
    ; // Telugu is not supported by the TTS engine, report an error
If you don't do this, eSpeak will use the language specified by the user in the TTS settings option.The eSpeak rules for Telugu uses the Telugu script, so you will need to specify words in that script. eSpeak has a feature for non-Latin languages where it uses English to speak Latin text. It should pronounce the numbers correctly.—

**Comment by vishwanadkavitha** [comment]
Dear Rhdunn/espeak ,
Please can you guide me how to add telugu language to the espeak tts engine. Thank you in advance.
Regards,kavitha

**Comment by rhdunn** [comment]
The eSpeak program already supports Telugu, so you don't need to do anything.

Android TTS requires the TTS engines to be installed separately. If you wanted to use eSpeak directly in your application, it would need to comply with the GPL license (making the source code available to users). You could modify the eSpeak for Android code to allow you to use it as a library, but I can't help you with that.

Using the Android TTS would allow users to use any other TTS engine that supported Telugu.

**Comment by hari-droid** [comment]
I am interested
