### ISSUE TITLE
how can i use mbrola voices in building for android to be added to the voices in espeakdata.zip in res/raw ?

### ISSUE THREAD

**Issue by omar-adel** [rhdunn/espeak#68]
I serached a lot but invain .
how can i use mbrola voices in building for android to be added to the voices in espeakdata.zip in res/raw and then listed in the voices list in android app ?
thanks

**Comment by rhdunn** [comment]
You would:

1.  Need a version of the MBROLA binary that supports Android (I don't believe this is supported);
2.  Install the MBROLA binary and voice data along side eSpeak in the eSpeak APK (I don't believe it is possible to install MBROLA globally on Android);
3.  Modify eSpeak to look in the location you install eSpeak and the voices in step (2).
