### ISSUE TITLE
Cannot find symbol variable raw in Android Studio

### ISSUE THREAD

**Issue by hermieweber** [rhdunn/espeak#72]
I am trying to build eSpeak Android, but I am getting the error "CheckVoiceData.java->Cannot find symbol variable raw".
Does anybody know what might go wrong here?
Thank you.
![android](https://cloud.githubusercontent.com/assets/12529995/8023618/bc740ca2-0d13-11e5-95af-c971f5395bb7.jpg)

**Comment by rhdunn** [comment]
The espeakdata zip file has not been built. You need to run:

    ./autogen.sh
    ./configure --with-gradle=<path-to-gradle>
    make espeakdata
    make jni

from a command like in the espeak source directory. The `--with-gradle` option is needed if you want to build the APK from command line. The `make jni` is needed as Android Studio did not support using the NDK and I haven't yet figured out how to integrate it into the NDK supported version.

**Comment by hermieweber** [comment]
I have a bit crazy approach. I try to build it using Visual Studio 2015. It seems to have support for NDK. 
Can you tell me what I have to actually do? Would I have to compile a library from the files located under espeak-android/src? Sorry for the question, I am somehow confused about the ".zip" in espeakdata.zip. Is it the actual voice data or a library or both?

**Comment by rhdunn** [comment]
There isn't a single build step on Windows. The autotools/Makefile system is designed for POSIX systems.

If you want to know what to do on Windows, read what commands the makefile is running.
